config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :role_users
  resources :roles
  resources :worker_projects
  resources :departments
  resources :password_resets
  resources :workers do
    collection do
      get :search
    end
  end 
   

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
   has_many :workers, dependent: :destroy, inverse_of: :department
   validates :name, presence: true

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Отдел успешно создан.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Отдел успешно обновлён.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Отдел успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.haml
= form_for @department do |f|
  = error_messages_for @department
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        = f.error_messages_for(:name)

  .actions.margin-small-top
    = f.submit nil, class: 'btn btn-primary'

app/views/departments/edit.html.haml
%h1 Изменить данные отдела

= render 'form'

= link_to 'Показать', @department
\|
= link_to 'Назад', departments_path

app/views/departments/index.html.haml
=breadcrumb_tag do
  %li.active
    Отделы
  %li
    Данные об отделе

.page-header
  %h1= t('headers.departments.index')

= link_to new_department_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.department')

.row
  .col-xs-12
    %table.table.table-hover
      %tbody
        - @departments.each do |department|
          %tr.active
            %th= Department.human_attribute_name(:name)
            %td= department.name



            %td
              = link_to department, class: 'btn btn-warning' do
                = fa_icon :eye
                = t('buttons.show')
              = link_to edit_department_path(department), class: 'btn btn-info' do
                = fa_icon :edit
                = t('buttons.edit')
              = link_to department, :method => :delete,
              :data => { :confirm => t('buttons.confirm.department') },
              class: 'btn btn-danger' do
                = fa_icon :times
                = t('buttons.destroy')
            %td

app/views/departments/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.departments.new')
  %li
    = link_to 'Отделы', departments_path
  %li Новый отдел
    

.page-header
  %h1= t('headers.departments.new')

= render 'form'

app/views/departments/show.html.haml
=breadcrumb_tag do
  %li.active
    = @department.name
  %li
    = link_to 'Отдел', department_path
  %li

%h1= @department.name

%dl
  %dt= Department.human_attribute_name(:name)
  %dd= @department.name