config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :role_users
  resources :roles
  resources :worker_projects
  resources :departments
  resources :password_resets
  resources :workers do
    collection do
      get :search
    end
  end 
   

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :worker_projects
  accepts_nested_attributes_for :worker_projects

  validates :name, length: {maximum: 30}, presence: true,
  uniqueness: {scope: [:start_date, :finish_date], message: "с такой датой начала и окончания уже существует" }
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Проект успешно создан.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Проект успешно обновлен.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Проект успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start_date, :finish_date, :price,
        {worker_projects_attributes: [:_destroy, :id, :worker_id]})
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  = error_messages_for @project
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        = f.error_messages_for(:name)
  .row
    .col-md-6
      .form-group
        = f.label :start_date
        .input-group.date.datepicker
          = f.text_field :start_date, value: lnil(f.object.start_date), class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:start_date)
  .row
    .col-md-6
      .form-group
        = f.label :finish_date
        .input-group.date.datepicker
          = f.text_field :finish_date, value: lnil(f.object.finish_date), class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:finish_date)
  .row
    .col-md-6
      .form-group
        = f.label :price
        .input-group
          = f.text_field :price, class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-ruble
        = f.error_messages_for(:price)



      .col_md-12
        = link_to_add_worker(f, f.object)
    -i = 0
    = f.fields_for(:worker_projects) do |fr|
      = fr.hidden_field(:id)
      = render("projects/one_worker_form", fr: fr, i: i + 1)

  .actions.margin-small-top
    = f.submit nil, class: 'btn btn-primary'

app/views/projects/_one_worker_form.html.haml
-# nested_start
.col-md-6
  %div{class: 'panel panel-'+ (i.kind_of?(Integer) ? 'success' : 'info')}
    .panel-heading
      Сотрудник
      = i
      %span.toright
        = link_to_remove_worker(fr)
      .clearfix
    .panel-body
      .row
        .col-md-6
          .form-group
            = fr.label :worker_id
            = fr.select(:worker_id,
            options_for_select(worker_options, fr.object.worker_id),
            {}, class: 'form-control')
            -# role_options ищите в roles_helper
            = fr.error_messages_for(:worker_id)
        
-# nested_finish

app/views/projects/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.projects.edit')
  %li
    = link_to(@project.name, @projects)
  %li
    = link_to 'Проекты', projects_path
  %li
    Изменение данных

.page-header
  %h1= t('headers.projects.edit')
  
= render 'form'

app/views/projects/index.html.haml
=breadcrumb_tag do
  %li.active
    Проекты
  %li
    Проект

.page-header
  %h1= t('headers.projects.index')

= link_to new_project_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.project')

.row
  .col-xs-12
    %table.table.table-hover
      %tbody
        - @projects.each do |project|
          %tr.active
            %th= Project.human_attribute_name(:name)
            %td= project.name
          %tr
            %th= Project.human_attribute_name(:start_date)
            %td= project.start_date
          %tr
            %th= Project.human_attribute_name(:finish_date)
            %td= project.finish_date
          %tr
            %th= Project.human_attribute_name(:price)
            %td= project.price
          %tr

            %td
              = link_to project, class: 'btn btn-warning' do
                = fa_icon :eye
                = t('buttons.show')
              = link_to edit_project_path(project), class: 'btn btn-info' do
                = fa_icon :edit
                = t('buttons.edit')
              = link_to project, :method => :delete,
              :data => { :confirm => t('buttons.confirm.project') },
              class: 'btn btn-danger' do
                = fa_icon :times
                = t('buttons.destroy')
            %td

app/views/projects/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.projects.new')
  %li
    = link_to 'Проекты', projects_path
  %li Новый проект
    

.page-header
  %h1= t('headers.projects.new')

= render 'form'

app/views/projects/show.html.haml
=breadcrumb_tag do
  %li.active
    = @project.name
  %li
    = link_to 'Проекты', project_path
  %li
    Проект

%h1= @project.name

%dl
  %dt= Project.human_attribute_name(:name)
  %dd= @project.name

  %dt= Project.human_attribute_name(:start_date)
  %dd= @project.start_date

  %dt= Project.human_attribute_name(:finish_date)
  %dd= @project.finish_date

  %dt= Project.human_attribute_name(:price)
  %dd= @project.price