config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :role_users
  resources :roles
  resources :worker_projects
  resources :departments
  resources :password_resets
  resources :workers do
    collection do
      get :search
    end
  end 
   

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :department
  has_many :worker_projects
  accepts_nested_attributes_for :department, reject_if: :all_blank
  accepts_nested_attributes_for :worker_projects

  validates :ln, length: {minimum: 2, maximum: 20}
  validates :fn, length: {minimum: 2, maximum: 20}
  validates :sn, length: {maximum: 20}
  validates :pas_number, length: {is: 6}, uniqueness: true
  validates :pas_serial, length: {is: 4}, uniqueness: true
  validates :inn, length: {is: 12}, uniqueness: true
  validates :birthday, presence: true
  validates :post, presence: true, length: {maximum: 30}

def self.search(params)
    result = Worker.eager_load(:department, :worker_projects, worker_projects: :project).references(:department)
    if params['project_id'].present?
      result = result.where("worker_projects.project_id = ?", params['project_id'])
    end
    if params['department_id'].present?
      result = result.where(department_id: params['department_id'])
    end
    if params['ln'].present?
      result = result.where(ln: params['ln'])
    end
    if params['fn'].present?
      result = result.where(fn: params['fn'])
    end
    if params['sn'].present?
      result = result.where(sn: params['sn'])
    end
    if params['birthday'].present?
      result = result.where(birthday: params['birthday'])
    end
    if params['post'].present?
      result = result.where(post: params['post'])
    end
    if params['inn'].present?
      result = result.where(inn: params['inn'])
    end
     if params['pas_number'].present?
      result = result.where(pas_number: params['pas_number'])
    end
     if params['pas_serial'].present?
      result = result.where(pas_serial: params['pas_serial'])
    end
     result.all
  end

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  def search
    if params.has_key?('search')
      @workers = Worker.search(params['search'])
    else
      @workers = []
    end
    params['search'] ||= {}
    @old_name=params.has_key?('search') ? params[:search][:name] : ""

  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Сотрудник успешно создан.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Сотрудник успешно обновлён.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Сотрудник успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:ln, :fn, :sn, :pas_number, :pas_serial, :inn, :birthday, :post, :department_id,
        {department_attributes:[:_destroy, :id, :name]})
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
  def new_department_form(form)
    form.fields_for(:department, Department.new) do |fr|
      render('workers/one_department_form', fr: fr)
    end
  end
  def worker_options()
    Worker.all.pluck('id')
  end
  def department_for_select
      Department.all.collect {|x| [x.name, x.id]}
  end
end

app/views/workers/_exist_department.html.haml
.row
  .col-md-12
    .form-group
      = f.label :department_id
      = f.select :department_id,  Department.all.map{|x| [x.name, x.id]}, {}, class: 'form-control'
      = f.error_messages_for(:department_id)

app/views/workers/_form.html.haml
= form_for @worker do |f|
  = error_messages_for @worker
  .row
    .col-md-6
      .form-group
        = f.label :ln
        = f.text_field :ln, class: 'form-control'
        = f.error_messages_for(:ln)
  .row
    .col-md-6
      .form-group
        = f.label :fn
        = f.text_field :fn, class: 'form-control'
        = f.error_messages_for(:fn)
  .row
    .col-md-6
      .form-group
        = f.label :sn
        = f.text_field :sn, class: 'form-control'
        = f.error_messages_for(:sn)
  .row
    .col-md-6
      .form-group
        = f.label :pas_number
        = f.text_field :pas_number, class: 'form-control'
        = f.error_messages_for(:pas_number)
  .row
    .col-md-6
      .form-group
        = f.label :pas_serial
        = f.text_field :pas_serial, class: 'form-control'
        = f.error_messages_for(:pas_serial)

  .row
    .col-md-6
      .form-group
        = f.label :inn
        = f.text_field :inn, class: 'form-control'
        = f.error_messages_for(:inn)


  .row
    .col-md-6
      .form-group
        = f.label :birthday
        .input-group.date.datepicker
          = f.text_field :birthday, value: lnil(f.object.birthday), class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:birthday)
  .row
    .col-md-6
      .form-group
        = f.label :post
        = f.text_field :post, class: 'form-control'
        = f.error_messages_for(:post)

  %fieldset
    %legend Поле для отдела
    %button.btn.btn-info#department-change-exist-btn Выбрать/Создать
    %div.left#department-change{"data-content-new": "#{new_department_form(f)}",
      "data-content-exist": "#{render 'exist_department', f: f}"}
      = f.fields_for(:department) do |fr|
        = fr.hidden_field(:id)
        = render('workers/one_department_form', fr: fr)  






  .actions.margin-small-top
  = f.submit nil, class: 'btn btn-primary'

app/views/workers/_one_department_form.html.haml
.row
  .col-md-6
    .form-group
      = fr.label :name
      = fr.text_area :name, class: 'form-control', rows: 1
      = fr.error_messages_for(:name)

app/views/workers/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.workers.edit')
  %li
    = link_to(@worker.ln, @worker)
  %li
    = link_to 'Сотрудник', workers_path
  %li
    Изменение данных

.page-header
  %h1= t('headers.workers.edit')
  
= render 'form'

app/views/workers/index.html.haml
=breadcrumb_tag do
  %li.active
    Сотрудники
  %li
    Данные о сотруднике

.page-header
  %h1= t('headers.workers.index')

= link_to new_worker_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.worker')

.row
  .col-xs-12
    %table.table.table-hover
      %tbody
        - @workers.each do |worker|
          %tr.active
            %th= Worker.human_attribute_name(:ln)
            %td= worker.ln
          %tr
            %th= Worker.human_attribute_name(:fn)
            %td= worker.fn
          %tr
            %th= Worker.human_attribute_name(:sn)
            %td= worker.sn
          %tr
            %th= Worker.human_attribute_name(:pas_number)
            %td= worker.pas_number
          %tr
            %th= Worker.human_attribute_name(:pas_serial)
            %td= worker.pas_serial
          %tr
            %th= Worker.human_attribute_name(:inn)
            %td= worker.inn
          %tr
            %th= Worker.human_attribute_name(:birthday)
            %td= worker.birthday
          %tr
            %th= Worker.human_attribute_name(:post)
            %td= worker.post
          %tr
            %th= Worker.human_attribute_name(:department)
            %td= worker.department.name
          %tr



            %td
              = link_to worker, class: 'btn btn-warning' do
                = fa_icon :eye
                = t('buttons.show')
              = link_to edit_worker_path(worker), class: 'btn btn-info' do
                = fa_icon :edit
                = t('buttons.edit')
              = link_to worker, :method => :delete,
              :data => { :confirm => t('buttons.confirm.worker') },
              class: 'btn btn-danger' do
                = fa_icon :times
                = t('buttons.destroy')
            %td

app/views/workers/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.workers.new')
  %li
    = link_to 'Сотрудник', workers_path
  %li Новый Сотрудник
    

.page-header
  %h1= t('headers.workers.new')

= render 'form'

app/views/workers/search.html.haml
= form_tag search_workers_path(), method: :get do
  .well
    %h3 Поиск
    .row
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:ln)
        =text_field_tag 'search[ln]', params['search']['ln'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:fn)
        =text_field_tag 'search[fn]', params['search']['fn'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:sn)
        =text_field_tag 'search[sn]', params['search']['sn'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:pas_serial)
        =text_field_tag 'search[pas_serial]', params['search']['pas_serial'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:pas_number)
        =text_field_tag 'search[pas_number]', params['search']['pas_number'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:inn)
        =text_field_tag 'search[itn]', params['search']['inn'],class: 'form-control'
      .col-md-4
        .form-group
        =Worker.human_attribute_name(:birthday)
        .input-group.date.datepicker
          =text_field_tag 'search[birthday]', params['search']['birthday'],class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar

      .col-md-4
        .form-group
        =Worker.human_attribute_name(:post)
        =text_field_tag 'search[post]', params['search']['post'],class: 'form-control'


    %h2 Поиск по атрибутам отделов
    .row
      .col-md-4
        .form-group
        =Department.human_attribute_name(:name)
        = select_tag 'search[name_dep]',options_for_select((Department.all.map{|x| [x.name]}.uniq),@old_name),
          {include_blank: true, class: 'form-control'}


  .actions
    =submit_tag "Найти", class: 'bnt btn-primary'
.page-header
  %h1= t('forms.worker_search.Результаты поиска') 
- if @workers.size > 0
  .well
    .row
      .form-group
        %dl
        - @workers.each do |worker|
          .col-xs-8.col-sm-8.col-lg-6
            .well
              %h5= "Сотрудник №" + worker.id.to_s
              %dt= Worker.human_attribute_name(:ln)
              %dd= worker.ln
              %dt= Worker.human_attribute_name(:fn)
              %dd= worker.fn
              %dt= Worker.human_attribute_name(:sn)
              %dd= worker.sn
              %dt= Worker.human_attribute_name(:pas_number)
              %dd= worker.pas_number
              %dt= Worker.human_attribute_name(:pas_serial)
              %dd= worker.pas_serial
              %dt= Worker.human_attribute_name(:inn)
              %dd= worker.inn
              %dt= Worker.human_attribute_name(:birthday)
              %dd= worker.birthday
              %dt= Worker.human_attribute_name(:post)
              %dd= worker.post
              %dt= Worker.human_attribute_name(:department)
              %dd= worker.department.name

app/views/workers/show.html.haml
=breadcrumb_tag do
  %li.active
    = @worker.ln
  %li
    = link_to 'Сотрудники', worker_path
  %li
    Сотрудник

%h1= @worker.ln

%dl
  %dt= Worker.human_attribute_name(:ln)
  %dd= @worker.ln

  %dt= Worker.human_attribute_name(:fn)
  %dd= @worker.fn

  %dt= Worker.human_attribute_name(:sn)
  %dd= @worker.sn

  %dt= Worker.human_attribute_name(:pas_number)
  %dd= @worker.pas_number

  %dt= Worker.human_attribute_name(:pas_serial)
  %dd= @worker.pas_serial

  %dt= Worker.human_attribute_name(:inn)
  %dd= @worker.inn

  %dt= Worker.human_attribute_name(:birthday)
  %dd= @worker.birthday

  %dt= Worker.human_attribute_name(:post)
  %dd= @worker.post

  %dt= Worker.human_attribute_name(:department)
  %dd= @worker.department.name